### ISSUE TITLE
Unsupported API Version error

### ISSUE THREAD

**Issue by apfister** [Esri/sonar#9]
- git clone'd the repo
- `npm install`'d
- `npm run create` then gives this error: 
`index.js uses an unsupported API version. Upgrade your claudia-api-builder or claudia-bot-builder dependency`

I've tried googling this error and all "solutions" point to updating `claudia-api-builder` and/or `claudia-bot-builder`. I've attempted to do both, but still get the same error.

Also, should `claudia.json` exist before [Step 3](https://github.com/Esri/sonar#quick-start)?

- claudia @ 3.3.1
- npm @ 5.7.1
- node @ 8.9.1

![screen shot 2018-03-09 at 4 10 42 pm](https://user-images.githubusercontent.com/5233042/37233688-d7009238-23b9-11e8-80a6-9b81f93b44bf.png)

**Comment by apfister** [comment]
temporary solution was to downgrade to claudia @ 2.14.2

**Comment by trumboosahil** [comment]
Hi 
I was facing same issue and in package.json i changed it to     "claudia-bot-builder": "^4", and it work
